apiVersion: namespaceclass.akuity.io/v1alpha1
kind: NamespaceClass
metadata:
  labels:
    app.kubernetes.io/name: namespaceclass
    app.kubernetes.io/managed-by: kustomize
  name: namespaceclass-sample-switch
spec:
  resources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: namespaceclass-sample-cm
      data:
        hello: switched
        version: v2

